// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqVJKz8h7Akl5wOkI3SGZ3_absSYkWCQ',
    appId: '1:886460912993:web:a83733218c2cdb6d83e120',
    messagingSenderId: '886460912993',
    projectId: 'watchwaves',
    authDomain: 'watchwaves.firebaseapp.com',
    storageBucket: 'watchwaves.appspot.com',
    measurementId: 'G-6535H0F89X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzmL0mJrdve1uopI-XgSEykxbgTqdVYE',
    appId: '1:886460912993:android:079d1372fcd4bf8683e120',
    messagingSenderId: '886460912993',
    projectId: 'watchwaves',
    storageBucket: 'watchwaves.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmbFa2vNptuo1QH7QYAr0FA3Breuq_2dg',
    appId: '1:886460912993:ios:b3a5c6e4f132677483e120',
    messagingSenderId: '886460912993',
    projectId: 'watchwaves',
    storageBucket: 'watchwaves.appspot.com',
    iosBundleId: 'com.fdevshashanksahu.projectint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmbFa2vNptuo1QH7QYAr0FA3Breuq_2dg',
    appId: '1:886460912993:ios:8c127723a1a07dc383e120',
    messagingSenderId: '886460912993',
    projectId: 'watchwaves',
    storageBucket: 'watchwaves.appspot.com',
    iosBundleId: 'com.fdevshashanksahu.projectint.RunnerTests',
  );
}
